sudo: required
language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - openjdk6

before_install:
  # show java version
  - java -version

script:
  - cd samples/client/petstore/java/jersey2-java6/ && mvn test

